// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Settings represents the application settings
 */
export class Settings {
    /**
     * Creates a new Settings instance.
     * @param {Partial<Settings>} [$$source = {}] - The source object to create the Settings.
     */
    constructor($$source = {}) {
        if (!("APITKey" in $$source)) {
            /**
             * API Key is loaded from environment variable GEXBOT_API_KEY first, then from config file
             * Note: omitempty is removed so API key is always written when present
             * @member
             * @type {string}
             */
            this["APITKey"] = "";
        }
        if (!("APISubscriptionTiers" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["APISubscriptionTiers"] = [];
        }
        if (!("CollectAllEndpoints" in $$source)) {
            /**
             * true = collect all available data, false = chart data only
             * @member
             * @type {boolean}
             */
            this["CollectAllEndpoints"] = false;
        }
        if (!("ActiveTickerRefreshRateMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ActiveTickerRefreshRateMs"] = 0;
        }
        if (!("DataCollectionRefreshRateMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["DataCollectionRefreshRateMs"] = 0;
        }
        if (!("DataDirectory" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["DataDirectory"] = "";
        }
        if (!("TrimDataStartTime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["TrimDataStartTime"] = "";
        }
        if (!("TrimDataEndTime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["TrimDataEndTime"] = "";
        }
        if (!("EnableDebug" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["EnableDebug"] = false;
        }
        if (!("HideConsole" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["HideConsole"] = false;
        }
        if (!("ShowCrosshair" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ShowCrosshair"] = false;
        }
        if (!("ShowDialogWarnings" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ShowDialogWarnings"] = false;
        }
        if (!("CrosshairColor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CrosshairColor"] = "";
        }
        if (!("CrosshairTextSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["CrosshairTextSize"] = 0;
        }
        if (!("CrosshairTextPlacement" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CrosshairTextPlacement"] = "";
        }
        if (!("CrosshairBackgroundOpacity" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["CrosshairBackgroundOpacity"] = 0;
        }
        if (!("CrosshairAxisMarkersEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["CrosshairAxisMarkersEnabled"] = false;
        }
        if (!("CrosshairAxisMarkerSide" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CrosshairAxisMarkerSide"] = "";
        }
        if (!("AlertDisplayTimeoutMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["AlertDisplayTimeoutMs"] = 0;
        }
        if (!("PriceColor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["PriceColor"] = "";
        }
        if (!("PriceFilterThresholdFuturesPercent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["PriceFilterThresholdFuturesPercent"] = 0;
        }
        if (!("PriceFilterThresholdStocksPercent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["PriceFilterThresholdStocksPercent"] = 0;
        }
        if (!("LegendOpacity" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["LegendOpacity"] = 0;
        }
        if (!("LegendFontColor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["LegendFontColor"] = "";
        }
        if (!("LegendFontSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["LegendFontSize"] = 0;
        }
        if (!("LegendBackgroundTransparent" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["LegendBackgroundTransparent"] = false;
        }
        if (!("LegendBackgroundColor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["LegendBackgroundColor"] = "";
        }
        if (!("PriceAxisLocation" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["PriceAxisLocation"] = "";
        }
        if (!("ChartTimezone" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ChartTimezone"] = "";
        }
        if (!("Alerts" in $$source)) {
            /**
             * @member
             * @type {any[]}
             */
            this["Alerts"] = [];
        }
        if (!("ProfileSettings" in $$source)) {
            /**
             * @member
             * @type {{ [_: string]: any }}
             */
            this["ProfileSettings"] = {};
        }
        if (!("Classic" in $$source)) {
            /**
             * @member
             * @type {{ [_: string]: any }}
             */
            this["Classic"] = {};
        }
        if (!("State" in $$source)) {
            /**
             * @member
             * @type {{ [_: string]: any }}
             */
            this["State"] = {};
        }
        if (!("Orderflow" in $$source)) {
            /**
             * @member
             * @type {{ [_: string]: any }}
             */
            this["Orderflow"] = {};
        }
        if (!("Charts" in $$source)) {
            /**
             * @member
             * @type {any[]}
             */
            this["Charts"] = [];
        }
        if (!("Tickers" in $$source)) {
            /**
             * @member
             * @type {any[]}
             */
            this["Tickers"] = [];
        }
        if (!("TickerConfigs" in $$source)) {
            /**
             * @member
             * @type {{ [_: string]: TickerConfig }}
             */
            this["TickerConfigs"] = {};
        }
        if (!("TickerOrder" in $$source)) {
            /**
             * User-defined ticker display order
             * @member
             * @type {string[]}
             */
            this["TickerOrder"] = [];
        }
        if (!("ChartColors" in $$source)) {
            /**
             * Color preferences for chart data series
             * @member
             * @type {{ [_: string]: string }}
             */
            this["ChartColors"] = {};
        }
        if (!("WindowWidth" in $$source)) {
            /**
             * Last saved window width
             * @member
             * @type {number}
             */
            this["WindowWidth"] = 0;
        }
        if (!("WindowHeight" in $$source)) {
            /**
             * Last saved window height
             * @member
             * @type {number}
             */
            this["WindowHeight"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Settings}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        const $$createField29_0 = $$createType1;
        const $$createField30_0 = $$createType2;
        const $$createField31_0 = $$createType2;
        const $$createField32_0 = $$createType2;
        const $$createField33_0 = $$createType2;
        const $$createField34_0 = $$createType1;
        const $$createField35_0 = $$createType1;
        const $$createField36_0 = $$createType4;
        const $$createField37_0 = $$createType0;
        const $$createField38_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("APISubscriptionTiers" in $$parsedSource) {
            $$parsedSource["APISubscriptionTiers"] = $$createField1_0($$parsedSource["APISubscriptionTiers"]);
        }
        if ("Alerts" in $$parsedSource) {
            $$parsedSource["Alerts"] = $$createField29_0($$parsedSource["Alerts"]);
        }
        if ("ProfileSettings" in $$parsedSource) {
            $$parsedSource["ProfileSettings"] = $$createField30_0($$parsedSource["ProfileSettings"]);
        }
        if ("Classic" in $$parsedSource) {
            $$parsedSource["Classic"] = $$createField31_0($$parsedSource["Classic"]);
        }
        if ("State" in $$parsedSource) {
            $$parsedSource["State"] = $$createField32_0($$parsedSource["State"]);
        }
        if ("Orderflow" in $$parsedSource) {
            $$parsedSource["Orderflow"] = $$createField33_0($$parsedSource["Orderflow"]);
        }
        if ("Charts" in $$parsedSource) {
            $$parsedSource["Charts"] = $$createField34_0($$parsedSource["Charts"]);
        }
        if ("Tickers" in $$parsedSource) {
            $$parsedSource["Tickers"] = $$createField35_0($$parsedSource["Tickers"]);
        }
        if ("TickerConfigs" in $$parsedSource) {
            $$parsedSource["TickerConfigs"] = $$createField36_0($$parsedSource["TickerConfigs"]);
        }
        if ("TickerOrder" in $$parsedSource) {
            $$parsedSource["TickerOrder"] = $$createField37_0($$parsedSource["TickerOrder"]);
        }
        if ("ChartColors" in $$parsedSource) {
            $$parsedSource["ChartColors"] = $$createField38_0($$parsedSource["ChartColors"]);
        }
        return new Settings(/** @type {Partial<Settings>} */($$parsedSource));
    }
}

/**
 * TickerConfig represents configuration for a single ticker
 */
export class TickerConfig {
    /**
     * Creates a new TickerConfig instance.
     * @param {Partial<TickerConfig>} [$$source = {}] - The source object to create the TickerConfig.
     */
    constructor($$source = {}) {
        if (!("Display" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Display"] = false;
        }
        if (!("CollectionEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["CollectionEnabled"] = false;
        }
        if (!("Priority" in $$source)) {
            /**
             * "high", "medium", "low"
             * @member
             * @type {string}
             */
            this["Priority"] = "";
        }
        if (!("RefreshRateMs" in $$source)) {
            /**
             * Optional override, 0 = use priority-based scheduling
             * @member
             * @type {number | null}
             */
            this["RefreshRateMs"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TickerConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TickerConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TickerConfig(/** @type {Partial<TickerConfig>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = TickerConfig.createFrom;
const $$createType4 = $Create.Map($Create.Any, $$createType3);
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
