// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct represents the main application
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./internal/config/models.js";

/**
 * CheckFirstRun checks if this is the first run (no API key configured)
 * @returns {$CancellablePromise<boolean>}
 */
export function CheckFirstRun() {
    return $Call.ByID(124085020);
}

/**
 * CompleteSetup completes the first-time setup
 * apiKey: API key (will be set as environment variable or in config)
 * subscriptionTiers: List of subscription tiers (e.g., ["classic", "state"])
 * initialTickers: List of initial tickers to enable
 * @param {string} apiKey
 * @param {string[]} subscriptionTiers
 * @param {string[]} initialTickers
 * @returns {$CancellablePromise<void>}
 */
export function CompleteSetup(apiKey, subscriptionTiers, initialTickers) {
    return $Call.ByID(507086583, apiKey, subscriptionTiers, initialTickers);
}

/**
 * GetAvailableDates returns a list of available dates (newest first) from data directories
 * Scans for directories matching "Tickers MM.DD.YYYY" pattern
 * Returns dates in "YYYY-MM-DD" format, sorted newest first
 * @returns {$CancellablePromise<string[]>}
 */
export function GetAvailableDates() {
    return $Call.ByID(1627172091).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetChartData serves chart data for chart windows
 * Loads data with limits and filters to reduce memory usage
 * ticker: Ticker symbol
 * dateStr: Date in format "2006-01-02" (YYYY-MM-DD)
 * @param {string} ticker
 * @param {string} dateStr
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function GetChartData(ticker, dateStr) {
    return $Call.ByID(3472344969, ticker, dateStr).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetCurrentMarketDate returns the current market date in Eastern Time as "YYYY-MM-DD"
 * Date rolls over at 8:30 AM ET (1 hour before market open)
 * @returns {$CancellablePromise<string>}
 */
export function GetCurrentMarketDate() {
    return $Call.ByID(1040982428);
}

/**
 * GetEnabledTickers returns the list of enabled tickers
 * Returns empty array if no tickers are enabled (doesn't crash)
 * Always reads from current settings to ensure it reflects the latest state
 * @returns {$CancellablePromise<string[]>}
 */
export function GetEnabledTickers() {
    return $Call.ByID(3633834339).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetMarketHoursLocal returns market open and close times in user's local timezone
 * Returns (openTime, closeTime) as "HH:MM" format strings
 * Note: Since we can't determine the user's browser timezone from Go, we return ET times
 * The frontend JavaScript will convert these to the user's local timezone
 * @returns {$CancellablePromise<[string, string]>}
 */
export function GetMarketHoursLocal() {
    return $Call.ByID(2386438601);
}

/**
 * GetNextMarketOpenLocalTime returns the next market open time in user's local timezone
 * Matches Python's get_next_market_open_time() logic exactly
 * Returns ISO format string in local timezone for JavaScript Date parsing
 * @returns {$CancellablePromise<string>}
 */
export function GetNextMarketOpenLocalTime() {
    return $Call.ByID(4021482484);
}

/**
 * GetNextMarketOpenTime returns the next market open time in ISO format (Eastern Time)
 * @returns {$CancellablePromise<string>}
 */
export function GetNextMarketOpenTime() {
    return $Call.ByID(105746055);
}

/**
 * GetSettings returns current settings
 * @returns {$CancellablePromise<config$0.Settings | null>}
 */
export function GetSettings() {
    return $Call.ByID(2554697378).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetTickerData loads ticker data from the database
 * dateStr is in format "2006-01-02" (YYYY-MM-DD)
 * Returns map[string][]interface{} where each key is a field name and value is an array of values
 * Returns empty data if database doesn't exist yet (data collection hasn't started)
 * CRITICAL: Uses LoadTickerData instead of LoadFromFile to skip profiles_blob and prevent memory issues
 * @param {string} ticker
 * @param {string} dateStr
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function GetTickerData(ticker, dateStr) {
    return $Call.ByID(2572115321, ticker, dateStr).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetTickerDataRange loads ticker data within a time range
 * dateStr is in format "2006-01-02" (YYYY-MM-DD)
 * Returns map[string][]interface{} where each key is a field name and value is an array of values
 * @param {string} ticker
 * @param {string} dateStr
 * @param {number} startTime
 * @param {number} endTime
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function GetTickerDataRange(ticker, dateStr, startTime, endTime) {
    return $Call.ByID(2955163430, ticker, dateStr, startTime, endTime).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetVersion returns the application version
 * @returns {$CancellablePromise<string>}
 */
export function GetVersion() {
    return $Call.ByID(1049863377);
}

/**
 * Greet returns a greeting message (for testing)
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function Greet(name) {
    return $Call.ByID(2659711170, name);
}

/**
 * IsMarketOpen checks if the market is currently open
 * @returns {$CancellablePromise<boolean>}
 */
export function IsMarketOpen() {
    return $Call.ByID(2919903461);
}

/**
 * LogFrontend logs a message from the frontend to the backend console and log file
 * This allows frontend errors to appear in the terminal window
 * @param {string} level
 * @param {string} message
 * @returns {$CancellablePromise<void>}
 */
export function LogFrontend(level, message) {
    return $Call.ByID(859772553, level, message);
}

/**
 * OpenChartWindow creates and opens a new chart window for a ticker
 * dateStr is optional - if empty, chart will use current market date
 * @param {string} ticker
 * @param {string} dateStr
 * @returns {$CancellablePromise<void>}
 */
export function OpenChartWindow(ticker, dateStr) {
    return $Call.ByID(3221280727, ticker, dateStr);
}

/**
 * RegisterTickerDisplay registers a ticker as being displayed in the frontend
 * @param {string} ticker
 * @returns {$CancellablePromise<void>}
 */
export function RegisterTickerDisplay(ticker) {
    return $Call.ByID(3357579540, ticker);
}

/**
 * ResizeMainWindow resizes the main window to the specified dimensions
 * @param {number} width
 * @param {number} height
 * @returns {$CancellablePromise<void>}
 */
export function ResizeMainWindow(width, height) {
    return $Call.ByID(3540397824, width, height);
}

/**
 * SaveSettings saves settings
 * Note: API key is preserved from existing settings (not overwritten by frontend)
 * @param {config$0.Settings | null} settings
 * @returns {$CancellablePromise<void>}
 */
export function SaveSettings(settings) {
    return $Call.ByID(1949631069, settings);
}

/**
 * SaveWindowSize saves the current window dimensions to settings
 * Uses lightweight SaveWindowDimensions to avoid full settings reload
 * @param {number} width
 * @param {number} height
 * @returns {$CancellablePromise<void>}
 */
export function SaveWindowSize(width, height) {
    return $Call.ByID(4029391749, width, height);
}

/**
 * SetApp sets the Wails application reference (called from main.go)
 * @param {any} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(4256893662, app);
}

/**
 * TestFrontendConnection is a simple test method that the frontend can call immediately
 * This verifies the frontend JavaScript is executing and can reach the backend
 * @returns {$CancellablePromise<string>}
 */
export function TestFrontendConnection() {
    return $Call.ByID(892614793);
}

/**
 * UnregisterTickerDisplay unregisters a ticker from being displayed
 * @param {string} ticker
 * @returns {$CancellablePromise<void>}
 */
export function UnregisterTickerDisplay(ticker) {
    return $Call.ByID(3435906149, ticker);
}

/**
 * VerifyDataCollection verifies that data collection is working
 * Returns a map with verification results
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function VerifyDataCollection() {
    return $Call.ByID(2182467256).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = config$0.Settings.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
